# Generated by Django 5.2 on 2025-04-10 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название аптеки')),
                ('address', models.CharField(max_length=500, verbose_name='Адрес')),
                ('network', models.CharField(blank=True, max_length=255, null=True, verbose_name='Сеть')),
                ('phones', models.TextField(blank=True, null=True, verbose_name='Телефоны')),
            ],
        ),
    ]
