# Generated by Django 5.2 on 2025-04-11 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugSearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_name', models.CharField(max_length=255)),
                ('pharmacies_with', models.PositiveIntegerField()),
                ('pharmacies_without', models.PositiveIntegerField()),
                ('searched_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
