# Generated by Django 5.2 on 2025-04-11 07:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_drugsearchhistory_drug_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='drugsearchhistory',
            name='drug_form',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
